version: '3.2'
services:
   app:
      image: highmed/bpe
      restart: on-failure
      volumes:
      -  type: bind
         source: ./app/conf
         target: /opt/bpe/conf
         read_only: true
      -  type: bind
         source: ./app/plugin
         target: /opt/bpe/plugin
         read_only: true
      -  type: bind
         source: ./app/process
         target: /opt/bpe/process
         read_only: true
      -  type: bind
         source: ./app/log
         target: /opt/bpe/log
      -  type: bind
         source: ./app/last_event
         target: /opt/bpe/last_event
      environment:
         TZ: Europe/Berlin
      networks:
         frontend:
            ipv4_address: 172.28.3.3
         backend:
            ipv4_address: 172.28.3.130
         fhir_bpe:
            ipv4_address: 172.28.2.3
      depends_on:
      - db
   db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: bpe
      networks:
         backend:
            ipv4_address: 172.28.3.131
      secrets:
      - postgres_password
secrets:
   postgres_password:
      file: ./db/conf/postgres_password
networks:
   frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         - subnet: 172.28.3.0/25
   backend:
      driver: bridge
      ipam:
         driver: default
         config:
         - subnet: 172.28.3.128/25
   fhir_bpe:
      external: true
