version: '3.9'
services:

   # ---- DIC-1 - FHIR ---------------------------------------------------------
   dic-1-fhir-proxy:
      image: highmed/fhir_proxy
      restart: on-failure
      volumes:
      - type: bind
        source: ./dic-1/fhir/proxy/ssl
        target: /usr/local/apache2/ssl
      environment:
         HTTPS_SERVER_NAME_PORT: dic-1:443
         APP_SERVER_IP: 172.20.1.3
      networks:
         internet:
            aliases:
            - dic-1
         dic-1-fhir-frontend:
            ipv4_address: 172.20.1.2
      depends_on:
      - dic-1-fhir-app
   dic-1-fhir-app:
      image: highmed/fhir
      restart: on-failure
      volumes:
      - type: bind
        source: ./dic-1/fhir/app/conf
        target: /opt/fhir/conf
      - type: bind
        source: ./dic-1/fhir/app/log
        target: /opt/fhir/log
      environment:
         TZ: Europe/Berlin
      networks:
         dic-1-fhir-frontend:
            ipv4_address: 172.20.1.3
         dic-1-fhir-backend:
            ipv4_address: 172.20.1.130
      depends_on:
      - dic-1-fhir-db
   dic-1-fhir-db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/dic-1-fhir-postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: fhir
      networks:
         dic-1-fhir-backend:
            ipv4_address: 172.20.1.131
      secrets:
      - dic-1-fhir-postgres_password

   # ---- DIC-1 - BPE ----------------------------------------------------------
   dic-1-bpe-app:
      image: highmed/bpe
      restart: on-failure
      volumes:
      - type: bind
        source: ./dic-1/bpe/app/conf
        target: /opt/bpe/conf
        read_only: true
      - type: bind
        source: ./dic-1/bpe/app/plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./dic-1/bpe/app/process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./dic-1/bpe/app/log
        target: /opt/bpe/log
      - type: bind
        source: ./dic-1/bpe/app/last_event
        target: /opt/bpe/last_event
      environment:
         TZ: Europe/Berlin
      networks:
         dic-1-bpe-frontend:
            ipv4_address: 172.20.2.2
         dic-1-bpe-backend:
            ipv4_address: 172.20.2.130
         internet:
      depends_on:
      - dic-1-bpe-db
      - dic-1-fhir-proxy
   dic-1-bpe-db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/dic-1-bpe-postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: bpe
      networks:
         dic-1-bpe-backend:
            ipv4_address: 172.20.2.131
      secrets:
      - dic-1-bpe-postgres_password

   # ---- ZARS - FHIR ---------------------------------------------------------
   zars-fhir-proxy:
      image: highmed/fhir_proxy
      restart: on-failure
      ports:
      - 443:443
      volumes:
      -  type: bind
         source: ./zars/fhir/proxy/ssl
         target: /usr/local/apache2/ssl
      environment:
         HTTPS_SERVER_NAME_PORT: zars:443
         APP_SERVER_IP: 172.30.1.3
      networks:
         internet:
            aliases:
            - zars
         zars-fhir-frontend:
            ipv4_address: 172.30.1.2
      depends_on:
      - zars-fhir-app
   zars-fhir-app:
      image: highmed/fhir
      restart: on-failure
      volumes:
      -  type: bind
         source: ./zars/fhir/app/conf
         target: /opt/fhir/conf
      -  type: bind
         source: ./zars/fhir/app/log
         target: /opt/fhir/log
      environment:
         TZ: Europe/Berlin
      networks:
         zars-fhir-frontend:
            ipv4_address: 172.30.1.3
         zars-fhir-backend:
            ipv4_address: 172.30.1.130
      depends_on:
      - zars-fhir-db
   zars-fhir-db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d fhir"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/zars-fhir-postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: fhir
      networks:
         zars-fhir-backend:
            ipv4_address: 172.30.1.131
      secrets:
      - zars-fhir-postgres_password

   # ---- ZARS - BPE ----------------------------------------------------------
   zars-bpe-app:
      image: highmed/bpe
      restart: on-failure
      volumes:
      -  type: bind
         source: ./zars/bpe/app/conf
         target: /opt/bpe/conf
         read_only: true
      -  type: bind
         source: ./zars/bpe/app/plugin
         target: /opt/bpe/plugin
         read_only: true
      -  type: bind
         source: ./zars/bpe/app/process
         target: /opt/bpe/process
         read_only: true
      -  type: bind
         source: ./zars/bpe/app/log
         target: /opt/bpe/log
      -  type: bind
         source: ./zars/bpe/app/last_event
         target: /opt/bpe/last_event
      environment:
         TZ: Europe/Berlin
      networks:
         zars-bpe-frontend:
            ipv4_address: 172.30.2.2
         zars-bpe-backend:
            ipv4_address: 172.30.2.130
         internet:
      depends_on:
      - zars-bpe-db
      - zars-fhir-proxy
   zars-bpe-db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/zars-bpe-postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: bpe
      networks:
         zars-bpe-backend:
            ipv4_address: 172.30.2.131
      secrets:
      - zars-bpe-postgres_password

secrets:
   dic-1-fhir-postgres_password:
      file: ./dic-1/fhir/db/conf/postgres_password
   dic-1-bpe-postgres_password:
      file: ./dic-1/bpe/db/conf/postgres_password

   zars-fhir-postgres_password:
      file: ./zars/fhir/db/conf/postgres_password
   zars-bpe-postgres_password:
      file: ./zars/bpe/db/conf/postgres_password

networks:
   internet:
      driver: bridge
   dic-1-fhir-frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.20.1.0/25
   dic-1-fhir-backend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.20.1.128/25
   dic-1-bpe-frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.20.2.0/25
   dic-1-bpe-backend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.20.2.128/25

   zars-fhir-frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.30.1.0/25
   zars-fhir-backend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.30.1.128/25
   zars-bpe-frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.30.2.0/25
   zars-bpe-backend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.30.2.128/25
